# This is the name of the workflow
name: Hello Workflow
#Runs on trigger 
on:
  push:
    branches:
      - main

# Jobs inside workflows
jobs:
  greet:
  # This is the GitHub runner
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to users
        run: echo "hello"

      - name: Say hello to username
        run: echo "hello $USER"
